[package]
name = "graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

futures = "0.3.17"
rocket = "0.5.0-rc.1"
async-graphql = "3.0"
async-graphql-rocket = "3.0.17"
web3 = "0.17.0"



